// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9095);

service /notification on ep0 {
    # Send a notification to a user
    #
    # + return - Notification sent 
    resource function post notifications() returns http:Accepted {
        return http:ACCEPTED;
    }
}
