openapi: 3.0.0
info:
  title: Account Management Service
  description: This service manages user accounts within FinFlux Microservices.
  version: "1.0.0"
servers:
  - url: 'https://api.finflux.com/account'
paths:
  /accounts:
    get:
      summary: List all accounts
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    post:
      summary: Create a new account
      responses:
        '201':
          description: Account created
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountNumber:
          type: string
        accountType:
          type: string
          enum: [checking, savings, loan]
        balance:
          type: number
          format: float
