apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: notifications
  projectName: FinFlux
  annotations:
    componentType: service
spec:
  inbound:
    - name: notifications
      port: 9095
      type: REST
      visibility: Project
      context: "/notification"
      schemaFilePath: openapi.yaml
