apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: tickets
  projectName: FinFlux
  annotations:
    componentType: service
spec:
  inbound:
    - name: tickets
      port: 3000
      type: REST
      visibility: Project
      context: .
      schemaFilePath: openapi.yaml
