// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

public type Transaction record {
    string id?;
    string accountNumber?;
    "deposit"|"withdrawal"|"transfer" 'type?;
    float amount?;
    string timestamp?;
};
