apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: transactions
  projectName: FinFlux
  annotations:
    componentType: service
spec:
  inbound:
    - name: transactions
      port: 3000
      type: REST
      visibility: Organization
      context: .
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
      - name: choreo:///kanushkagayan/wknh/xxkhcb/dec73/v1.0/PROJECT
        connectionConfig: 01ee843b-08c3-1076-96c6-8749a101ced0
        env:
          - from: ServiceURL
            to: SERVICE_URL
