openapi: 3.0.0
info:
  title: Customer Support Service
  description: Manages customer interactions and support tickets for FinFlux Microservices.
  version: "1.0.0"
servers:
  - url: 'https://api.finflux.com/support'
paths:
  /tickets:
    get:
      summary: Get a list of support tickets
      responses:
        '200':
          description: A list of support tickets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
    post:
      summary: Create a new support ticket
      responses:
        '201':
          description: Support ticket created
components:
  schemas:
    Ticket:
      type: object
      properties:
        id:
          type: string
          format: uuid
        subject:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [open, in_progress, resolved, closed]
