apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: accounts
  projectName: FinFlux
  annotations:
    componentType: service
spec:
  inbound:
    - name: accounts
      port: 9094
      type: REST
      visibility: Project
      context: "/accounts"
      schemaFilePath: openapi.yaml
